/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LoanController;
import Controller.MediaCopyController;
import Controller.MediaSearchController;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashSet;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class UpdateCopy extends javax.swing.JFrame {

    static String extMediaID; 
    boolean wantToChange = true;
    LinkedHashSet<Integer> rowList = new LinkedHashSet<Integer>(); 

    
    /**
     * Creates new form UpdateCopy
     */
    public UpdateCopy() {
        
        initComponents();
        updateTable(extMediaID);
        
         copyTable.getModel().addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(TableModelEvent changeMedia) {
               
                
                 if (wantToChange == true)
                 {
                   int row = changeMedia.getFirstRow();
                   //int column = changeMedia.getColumn();
                   //DefaultTableModel model = (DefaultTableModel)changeMedia.getSource();
                   //String columnName = model.getColumnName(column);
                   //Object data =  mediaSearchTable.getModel().getValueAt(row, 0);
                   //DefaultTableModel model = (DefaultTableModel)mediaSearchTable.getModel();
                   //Object dataObject = model.getDataVector().elementAt(mediaSearchTable.getSelectedRow());
               
                   rowList.add(row);
                 }

            }
            
        });
                
    }
    
     public static void auth() {
        
        switch(Login.userCategory) {
            case 1:
                
            break;
            
            case 2:
                
            break;
            
            case 3:
                
            break;
            
            case 4:
                
            break;
            
            case 5:
                
            break;
            
            default:
                
            break;
        }
        
    }
    
    public void loanRow() {
        
        int loanRow = 0;
        loanRow = copyTable.getSelectedRow();
        String loan = copyTable.getModel().getValueAt(loanRow, 0).toString();
        
        
        
        
    }  
    
    public void emptyTable() {
        
        wantToChange = false;
         
        final String ERASE = null;
        int x = 0;
        int columns = 10;
               
        for (x=0; x < 50; x++) {
            for (int i=0; i < columns; i++) {
                copyTable.getModel().setValueAt(ERASE, x, i);
            }   
        }
        
        rowList.clear();
        
    }                   
    
    public static void mediaIDPass(String mediaTest) {
       
        extMediaID = mediaTest;
                
    }
    
    public void updateTable(String mediaID) {
        
        ArrayList results = MediaCopyController.listCopies(mediaID);
   
        String status;
        
        int size = results.size();
        int columns = 4;
        int halfsize = size/columns;
       
        int j = 0;
        int x = j;
        int y = 0;
               
        for (x=0; x < halfsize; x++) {
            
            String returnedStatus = LoanController.checkStatus(results.get(y).toString());
            if(returnedStatus.equals("1")) {
                status = "Tillgänglig";
            }
            else {
                status = "Utlånad";
            }
       
            copyTable.getModel().setValueAt(status, x, 4);
            y = y + 4;
            
            for (int i=0; i < columns; i++) {
                copyTable.getModel().setValueAt(results.get(j), x, i);
                j++;
            }
        }
        
    
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        copyTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        back = new javax.swing.JButton();
        loan = new javax.swing.JButton();
        copy2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        errorLoaned = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        copyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Streckkod", "Media ID", "Titel", "Placering", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(copyTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Exemplarshantering");

        update.setText("Spara");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        remove.setText("Ta bort");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        back.setText("Tillbaka");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        loan.setText("Lägg i lånekorgen");
        loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanActionPerformed(evt);
            }
        });

        copy2.setText("Checka ut / kvitto");
        copy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copy2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Låna exemplar");

        errorLoaned.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        errorLoaned.setForeground(new java.awt.Color(255, 0, 0));
        errorLoaned.setText("Boken är utlånad välj ett annat exemplar eller vänta tills den blir tillgänglig");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copy2)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(errorLoaned)))
                        .addGap(101, 101, 101))))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addComponent(back)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(errorLoaned, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(remove)
                    .addComponent(loan)
                    .addComponent(copy2))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
         //ArrayList<String> mediaData = new ArrayList<String>(); 
        Iterator<Integer> iter = rowList.iterator();

        while(iter.hasNext()) {  
        
          DefaultTableModel model = (DefaultTableModel)copyTable.getModel();
          Object dataObject = model.getDataVector().elementAt(iter.next());
          String tableData = dataObject.toString();
          String strArray[] = tableData.split(",");
          String barcodeID = strArray[0];
          barcodeID = barcodeID.replace("[", "");
          
          if(barcodeID.equals("null")) {
            MediaCopyController.insertCopy(strArray);
          }
          else {
            MediaCopyController.updateCopy(strArray, barcodeID);
          }
          
        
        }
    }//GEN-LAST:event_updateActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        
    }//GEN-LAST:event_removeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        MediaSearch.search();
    }//GEN-LAST:event_backActionPerformed

    private void loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanActionPerformed
        int currentRow = copyTable.getSelectedRow();
        String barcodeID = copyTable.getModel().getValueAt(currentRow, 0).toString();        
        String available = copyTable.getModel().getValueAt(currentRow, 4).toString();
        System.out.println(available);
        if(available.equals("Tillgänglig")) {
            LoanController.addToBasket(barcodeID, Login.userID, extMediaID);    
        }
        else {
            System.out.print("Inte tillgänglig");
        }
    }//GEN-LAST:event_loanActionPerformed

    private void copy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copy2ActionPerformed

    public static void copy() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                auth();
                new UpdateCopy().setVisible(true);
            }
        });
                       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton copy2;
    private javax.swing.JTable copyTable;
    private javax.swing.JLabel errorLoaned;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loan;
    private javax.swing.JButton remove;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}